import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-480 w-full bg-[conic-gradient(at_right,_var(--tw-gradient-stops))] from-gray-300 via-violet-400 to-red-600">
        <h1 className="h-480 h-full text-3xl font-bold underline text-white">
          Hello First step to create our Bakery Website with Analytics
        </h1>
      </main>
    </>
  );
}
