/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_mobile_analytics_app_id: "c9a13052aaf544f7881538b9ec87d791",
  aws_mobile_analytics_app_region: "ap-south-1",
  aws_appsync_graphqlEndpoint:
    "https://s2ozncbwqffsnnzlfw5dms4biy.appsync-api.ap-south-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-south-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-scvbclykpzbttnxmzbmdbs47ba",
  aws_cognito_identity_pool_id:
    "ap-south-1:669ea846-7dc8-40ee-8eb4-5ccf8729cb31",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_bKBvN1JOY",
  aws_user_pools_web_client_id: "70agir16g1gldphv02n5k49csc",
  oauth: {
    domain: "favouritebakery-cogniauth-dev.auth.ap-south-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://bakery.vishnupatekar.com/",
    redirectSignOut: "https://bakery.vishnupatekar.com/auth/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ["FACEBOOK", "GOOGLE"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_bots: "enable",
  aws_bots_config: [
    {
      name: "OrderFlowers_dev",
      alias: "$LATEST",
      region: "us-west-2",
    },
  ],
};

export default awsmobile;
